"""SQLAlchemy ORM models — schema reference for GridSense AI (no real DB required)."""
from __future__ import annotations
from datetime import datetime
from sqlalchemy import Column, String, Float, Integer, Boolean, DateTime, Text
from sqlalchemy.orm import DeclarativeBase


class Base(DeclarativeBase):
    """Base class for all ORM models."""
    pass


class TransformerAsset(Base):
    """Distribution transformer asset record."""

    __tablename__ = "transformer_assets"
    id = Column(String, primary_key=True)
    name = Column(String, nullable=False)
    location = Column(String)
    rated_kva = Column(Float)
    installation_date = Column(DateTime)
    is_degrading = Column(Boolean, default=False)


class TransformerReading(Base):
    """DTM sensor reading for a transformer."""

    __tablename__ = "transformer_readings"
    id = Column(String, primary_key=True)
    transformer_id = Column(String, nullable=False, index=True)
    timestamp = Column(DateTime, nullable=False)
    Va = Column(Float)
    Vb = Column(Float)
    Vc = Column(Float)
    Ia = Column(Float)
    Ib = Column(Float)
    Ic = Column(Float)
    oil_temp = Column(Float)
    power_factor = Column(Float)
    thd_pct = Column(Float)
    active_power_kw = Column(Float)
    reactive_power_kvar = Column(Float)
    tamper_flag = Column(Boolean, default=False)
    anomaly_score = Column(Float, nullable=True)


class MeterReading(Base):
    """Smart meter reading."""

    __tablename__ = "meter_readings"
    id = Column(String, primary_key=True)
    meter_id = Column(String, nullable=False, index=True)
    transformer_id = Column(String, nullable=False, index=True)
    timestamp = Column(DateTime, nullable=False)
    active_power_kw = Column(Float)
    reactive_power_kvar = Column(Float)
    tamper_flag = Column(Boolean, default=False)
    consumption_drop_pct = Column(Float, nullable=True)


class Alert(Base):
    """Anomaly alert generated by ML scoring."""

    __tablename__ = "alerts"
    id = Column(String, primary_key=True)
    transformer_id = Column(String, nullable=False, index=True)
    timestamp = Column(DateTime, nullable=False)
    severity = Column(String, nullable=False)
    anomaly_score = Column(Float)
    ewma_score = Column(Float)
    hours_to_failure = Column(Float, nullable=True)
    status = Column(String, default="ACTIVE")
    message = Column(Text)


class WorkOrder(Base):
    """Field engineer work order generated by AI diagnosis."""

    __tablename__ = "work_orders"
    id = Column(String, primary_key=True)
    transformer_id = Column(String, nullable=False)
    alert_id = Column(String, nullable=True)
    created_at = Column(DateTime, nullable=False)
    status = Column(String, default="PENDING")
    fault_type = Column(String)
    priority = Column(String)
    recommended_action = Column(Text)
    tools_needed = Column(String)
    estimated_repair_hours = Column(Float)
    evidence = Column(Text)
