"""Pydantic v2 schemas for alerts."""
from __future__ import annotations
from datetime import datetime
from enum import Enum
from typing import Optional
from pydantic import BaseModel, ConfigDict


class AlertSeverity(str, Enum):
    """Alert severity level."""

    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class AlertSchema(BaseModel):
    """Anomaly alert generated by the ML scoring system."""

    model_config = ConfigDict(from_attributes=True)

    id: str
    transformer_id: str
    timestamp: datetime
    severity: AlertSeverity
    anomaly_score: float
    ewma_score: float
    hours_to_failure: Optional[float] = None
    status: str = "ACTIVE"
    message: str
